import React from 'react';
import Page from './Page';

const FormPage = ({id}) => (<Page singleMode={true} id={id}>
    <div className="f2 mb2">Sale offer</div>
    <div>This is the offer generated by Pricing App</div>
    <div className="cf w-100 mt4">
        <div className=" fl w-50 bg-washed-blue vh-25 pa3">
            Some inputs here
            <form class=" container form-horizontal" method="post" action="createpdf.php">
                <fieldset>
                    <div class="col-md-12 text-left">
                            <select>
                                <option value="volvo">Artur Sieklucki</option>
                                <option value="saab">Magdalena Jońska</option>
                                <option value="opel">Natalia Tyszkiwicz</option>
                            </select>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input" placeholder="Site name" aria-describedby="inputGroup-sizing-default"/>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input" placeholder="Client name" aria-describedby="inputGroup-sizing-default"/>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        </div>
                        <input type="date" class="form-control" aria-label="Sizing example input" placeholder="Date" aria-describedby="inputGroup-sizing-default"/>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input" placeholder="Name name" aria-describedby="inputGroup-sizing-default"/>
                    </div>
                    <div class="input-group mb-3">
                    <input type="text" class="form-control" aria-label="Text input with checkbox"/>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12 text-left">
                            <select>
                                <option value="volvo">PMS v. PRO</option>
                                <option value="saab">PMS v. LITE</option>
                                <option value="opel">IBE</option>
                                <option value="audi">Housekeeping app</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group shadow-textarea">
                        <textarea id="comment-area" class="form-control z-depth-1" id="exampleFormControlTextarea6" placeholder="Additional comments" rows="5" placeholder="Write something here..."></textarea>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</Page>);

export default FormPage;